dashboard/urls.py
from django.urls import path
from dashboard import views
app_name = 'dashboard'
urlpatterns = [ 
    path('create', views.dashboard_index ,name="index"),
    path('libraries', views.dashboard_libraries ,name="libraries"),
    path('lib_scan/<int:lib_id>', views.library_scan , name="lib_scan"),
    path('process_data/<int:lib_id>', views.process_data , name="process_data"),
    path('delete_librabry/<int:librabry_id>', views.delete_librabry , name="delete_librabry"),
   
    

    
    


    
 
]

home/urls.py
from django.urls import path
from home import views
app_name = 'home'
urlpatterns = [ 
    
    path('', views.home_login , name="login"),
    path('logout', views.home_logout ,name="logout"),
    path('profile', views.home_profile ,name="profile"),


]

vulncheck/urls.py
from django.contrib import admin
from django.urls import path
from home import urls as home_urls
from mainmenu import urls as mainmenu_urls
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from dashboard import urls as dashboard_urls

urlpatterns = [
    path('', include(home_urls, namespace="home")),
    path('mainmenu/', include(mainmenu_urls, namespace="mainmenu")),
    path('dashboard/', include(dashboard_urls, namespace="dashboard")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.site.site_header = 'WEATHER'
admin.site.site_title = 'WEATHER'

dashboard/models.py
from django.db import models


class Library(models.Model):
    
    STATUS = (
        ('', '------------'),
        ('text', 'From Text Data'),
        ('csv', 'From CSV'),
        ('api', 'From API  '),    
    )

    application_name = models.CharField(default=None ,max_length=100)
    library_list = models.FileField(blank=True , null = True , upload_to='uploads/')
    data_mode = models.CharField(blank=True ,null=True, default='no' ,max_length=100 , choices = STATUS)
    created_at = models.DateField(default=None)
    updated_at = models.DateField(default=None)
    created_by = models.IntegerField(default=None)

    def __str__(self):
        return '%s' % self.application_name

class CVE_Scan(models.Model):
    

    cve_name = models.CharField(default=None ,max_length=100)


    def __str__(self):
        return '%s' % self.cve_name

dashboard/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import MaxValueValidator
from dashboard.models import Library ,CVE_Scan 

# model form 
from django.db import models
# from django.forms import ModelForm , Textarea , ModelChoiceField , Select  


class Library_Form(forms.ModelForm):

    class Meta:
        model = Library
        
        
        fields = ['application_name','library_list' ]

             
        widgets = {
            
            'application_name': forms.TextInput(attrs={
                "type" : "text",
                "class":"form-control"
            }),
            'library_list': forms.ClearableFileInput(attrs={
                "class":"form-control",
                "id":"picture",
                "type" : "file",
            }),
            'data_mode': forms.Select(attrs={
                "type" : "text",
                "class":"form-control custom-select",
               
            }),
           
        }

dashboard/views.py
from django.shortcuts import render
import calendar
from datetime import datetime
from django.contrib.auth.decorators import login_required , permission_required
from django.urls.base import translate_url
from requests.api import head
from pypi_simple import PyPISimple 
from dashboard.forms import Library_Form 
from dashboard.models import  Library
from django.contrib import messages
from django.utils import timezone
from django.urls import reverse
from django.http import HttpResponseRedirect
import vulners  
from django.core.mail import send_mail
import random
import pandas as pd
import requests
import json
from io import StringIO
import base64

from sklearn.cluster import KMeans
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from matplotlib import pyplot as plt
from time import sleep



@login_required
def dashboard_index(request):
    form = None
    url = "dashboard/index.html" 
    if request.method == 'POST':
        form = Library_Form(request.POST, request.FILES)
        if(form.is_valid()):
            data = form.save(commit=False)
        
            
            data.created_at = timezone.now()
            data.updated_at = timezone.now()
            data.created_by = request.user.id   
            data.save()
            messages.add_message(request, messages.INFO, 'File saved')
            return HttpResponseRedirect(reverse('dashboard:libraries'))
     
    else:
        form = Library_Form()
    
    context = {
         
        'title': "Upload Project  DataSet",
        'form':form
        
    } 
     
    return render(request , url , context)






def dashboard_libraries(request):
    libraries = Library.objects.all().order_by('-id')
    url = "dashboard/list_librabries.html" 
    # send_mail(
    #     'Payment',
    #     'find payment.',
    #     'kidkudzy@gmail.com',
    #     ['kmakufa@outlook.com', 'promiseksystems@gmail.com'],
    #     fail_silently=False,
    # )
    context = {
        
        'title': "DATA SETS",
        'libraries':libraries
        
    } 


    return render(request , url , context)



@login_required
def library_scan(request ,lib_id=None):
    library = Library.objects.filter(id=lib_id).order_by('-id')
    # f = open(library[0].library_list.path, "r")
    # print("------------------")

    # lines = f.readlines()


    
    # # for line in lines:
    # #     print(line)
    # # print("------------------")
    # f.close()

    # _________________________________
    df = pd.read_csv(library[0].library_list.path, delimiter=',')
    tuples = [tuple(x) for x in df.values]

   
    context = {
        "item":library[0], 
        "lines":tuples,
    }
    return render(request, 'dashboard/library_view.html', context)
    
    
@login_required
def process_data(request ,lib_id=None):
    library = Library.objects.get(id=lib_id)
    title = ""
    
    data = []
    age = []
    sales = []

    df1_age = []
    df1_sales = []

    df2_age = []
    df2_sales = []
    pie_data = []
    sleep(5)
    if library.data_mode  == "csv":
        filename = library.library_list

        df = pd.read_csv(filename.path, delimiter=',' )
        # 1 table description
        table_description = df.describe().to_html(justify='left').replace('<table border="1" class="dataframe">','<table class="table table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">')
        print(df.describe().values[0].tolist())
        for item in df.describe().values.tolist()[:-1] :
            
            pie_data.append(item[0])
        print(pie_data)
        # 2 plot table data
        age = df['Age'].values.tolist()
        sales = df['Sales'].values.tolist()

        # kmeans

        km = KMeans(n_clusters=3)
        y_predicted = km.fit_predict(df[['Age','Sales']])
        df['cluster'] = y_predicted
        
        df1 = df[df.cluster==0]
        df2 = df[df.cluster==1]

        df1_age = df1['Age'].values.tolist()
        df1_sales = df1['Sales'].values.tolist()

        df2_age = df2['Age'].values.tolist()
        df2_sales = df2['Sales'].values.tolist()

        # table for clusters

        table_clusters = df.to_html(justify='left').replace('<table border="1" class="dataframe">','<table id="datatable" class="table table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">')



       
        
        title = "Graphs for " +filename.path

    if library.data_mode  == "api":
        response = requests.get('https://api.openweathermap.org/data/2.5/forecast?id=890299&units=metric&appid=9b63dca2ced4e2d6ad7f4f01698d7a45')
        if response.status_code == 200 and 'application/json' in response.headers.get('Content-Type',''):
            result = response.json()
            data = result['list']


        else:
            print("error loading info")
        title = "Pulling 5 Day data focused for Harare before Hadoop implementation   "
    context = {
        'table_description':table_description ,
        'table_clusters':table_clusters,
        'age':age,
        'sales':sales,
        'df1_age':df1_age,
        'df1_sales':df1_sales,
        'df2_age':df2_age,
        'df2_sales':df2_sales,
        "item":library,
        "data":data ,
        "title":title,
        'pie_data':pie_data
       
    }
    return render(request, "dashboard/api_process.html", context)
@login_required
def delete_librabry(request ,librabry_id=None):
    library = Library.objects.get(pk=librabry_id)
    library.delete()
    messages.add_message(request, messages.INFO, 'Library deleted')
    return HttpResponseRedirect('/dashboard/libraries')

dashboard/templates/dashboard/api_process.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

<div class="row mb-5">
  <div class="col-6">  
     <h4>Data Description</h4>
      
     {{table_description|safe}}
   
  </div>
  <div class="col-6"> 
    <canvas id="myChart" width="400" height="300"></canvas>
  </div>
</div>

<div class="row">
  <div class="col-12">  
     <h4>Scatter Diagram</h4>

     <div id="myDiv"></div>
  </div>

</div>

<div class="row">
  <div class="col-12">  
     <h4>KMEANS CLUSTERS</h4>

     <div id="kmeans_clust"></div>
  </div>

</div>

<div class="row mb-5">
  <div class="col-12">  
     <h4>Clusters Table</h4>
      
     {{table_clusters|safe}}
   
  </div>

</div>




  {% endblock %}


  {% block footer %}
         <!-- Required datatable js -->
     <script src="{% static "admin/assets/libs/datatables.net/js/jquery.dataTables.min.js" %}"></script>
     <script src="{% static "admin/assets/libs/datatables.net-bs4/js/dataTables.bootstrap4.min.js" %}"></script>
     <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

     <!-- Datatable init js -->
     <script src="{% static "admin/assets/js/pages/datatables.init.js" %}"></script>
    <script src="https://cdn.plot.ly/plotly-2.6.3.min.js"></script>


    <script type = "text/javascript">
   

      var all_scatter = {
        x: {{age|safe}},
        y: {{sales|safe}},
        mode: 'markers',
        type: 'scatter',
        marker: {
          color: "blue"
        }
      };


       var cluster_0 = {
        x: {{df1_age|safe}},
        y: {{df1_sales|safe}},
        mode: 'markers',
        type: 'scatter',
         marker: {
          color: "red"
        }
      };

       var cluster_1 = {
        x: {{df2_age|safe}},
        y: {{df2_sales|safe}},
        mode: 'markers',
        type: 'scatter',
         marker: {
          color: "green"
        }
      };


      {% comment %} alert(trace1.x[0]); {% endcomment %}

      var data = [all_scatter];
      Plotly.newPlot('myDiv', data, {}, {showSendToCloud: true});

      Plotly.newPlot('kmeans_clust', [cluster_0,cluster_1], {}, {showSendToCloud: true});
      {% comment %} Plotly.newPlot('kmeans_clust', [], {}, {showSendToCloud: true}); {% endcomment %}
      
    
    </script>

    <script>
const ctx = document.getElementById('myChart').getContext('2d');
const myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: ['Count', 'Mean', 'STD', 'Min', '25%', '50%' , '75%'],
        datasets: [{
            label: '# of Sales',
            data: {{pie_data|safe}},
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            y: {
                beginAtZero: true
            }
        }
    }
});
</script>
  {% endblock %}

dashboard/templates/dashboard/index.html
{% extends 'base.html' %}

{% load static %}
{% block header %}
    <link href="{% static "admin/assets/libs/bootstrap-datepicker/css/bootstrap-datepicker.min.css" %}" rel="stylesheet">
{% endblock %}
{% block content %}

<form action="" method="post" autocomplete="off" enctype="multipart/form-data">{% csrf_token %}
<div class="row">
    <div class="col-lg-6">
        <div class="card">  
            <div class="card-body">

                
                <div class="form-group mb-4">
                  
                    <label>Dataset Name</label>
                    <div class="input-group">
                        {{ form.application_name }}
                        
                    </div>
                    <div class="text-danger"> {{ form.application_name.errors }}</div>
                </div>

                     <div class="form-group mb-4">
                  
                    <label>{{ form.data_mode.label_tag}}</label>
                    <div class="input-group">
                        {{ form.data_mode }}
                        
                    </div>
                    <div class="text-danger"> {{ form.data_mode.errors }}</div>
                </div>
             
             

                

                    

                
            </div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="card">
            <div class="card-body">

                <div class="form-group mb-4 data-file">
                    
                    <label>Dataset File</label>
                    <div class="input-group">
                        {{ form.library_list }}
                    </div>
                    <div class="text-danger"> {{ form.library_list.errors }}</div>
                </div>
                
                

        
                <br>
            </div>
              
                

            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12">
     
      <input type="submit" value="Save" class="btn btn-success float-left">
    </div>
  </div>
</form>
{% endblock %}


{% block footer %}

    <script>
        $('#id_data_mode').on('change', function() {
            if(this.value == "csv" | this.value == "text"){
                $('.data-file').css("display", 'block');
             
            }else{
                $('.data-file').css("display", 'none');
             
            }
        });
    </script>
    <script src="{% static "admin/assets/libs/bootstrap-datepicker/js/bootstrap-datepicker.min.js" %}"></script>
    <script src="{% static "admin/assets/js/pages/form-advanced.init.js" %}"></script>
    <script src="{% static "admin/assets/libs/bootstrap-maxlength/bootstrap-maxlength.min.js" %}"></script>
{% endblock %}

dashboard/templates/dashboard/list_librabries.html
{% extends "base.html" %}

{% load static %}
{% block header %}
    <link href="{% static "admin/assets/libs/bootstrap-datepicker/css/bootstrap-datepicker.min.css" %}" rel="stylesheet">
    <style>
        input[type="text"]:disabled {
        background: #dddddd;
}
    </style>
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-12">
        
        <a href="{% url 'dashboard:index' %}" class="btn btn-lg btn-success float-right">New Dataset</a>
     
    </div>
    <br>
</div>



<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">

             
                <table class="table table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                    <thead>
                    <tr>
                        
                        <th>DataSet Name </th>
                        
                        <th>Library list</th>
                     
                        <th>Actions  </th>
                        
                    
                    </tr>
                    </thead>


                    <tbody>
                 
                    {% for item in libraries %}
                        <tr>
                            <td>{{item.application_name}}</td>
                           
                        
                             <td>{{item.library_list}}</td>
                         

                            
                      
                        
                           
                        
                        
                            <td>
   
                                
                                <a href="{% url  'dashboard:process_data' item.id  %}" class="btn btn-outline-primary waves-effect waves-light" >Generate Graphs</a>
                                <a href="#" class="btn btn-outline-success waves-effect waves-light" >Edit</a>
                                <a href="{% url  'dashboard:delete_librabry' item.id %}" class="btn btn-outline-danger waves-effect waves-light" onclick="alert('Are you sure you want to delete')" >Delete</a>
                               
                            </td>
                 {% endfor %}        
                        </tr>
                   
               
              
                    </tbody>
                </table>

            </div>
        </div>
    </div> <!-- end col -->

</div> <!-- end row -->

{% endblock %}
    
{% block footer %}


  
<!-- datetime -->
<script src="{% static "admin/assets/libs/bootstrap-datepicker/js/bootstrap-datepicker.min.js" %}"></script>
<script src="{% static "admin/assets/js/pages/form-advanced.init.js" %}"></script>
<script src="{% static "admin/assets/libs/bootstrap-maxlength/bootstrap-maxlength.min.js" %}"></script>
     <!-- Required datatable js -->
     <script src="{% static "admin/assets/libs/datatables.net/js/jquery.dataTables.min.js" %}"></script>
     <script src="{% static "admin/assets/libs/datatables.net-bs4/js/dataTables.bootstrap4.min.js" %}"></script>

     <!-- Datatable init js -->
     <script src="{% static "admin/assets/js/pages/datatables.init.js" %}"></script>
{% endblock %}